requirements.txt
spinnaker-monitoring/__main__.py
spinnaker-monitoring/command_processor.py
spinnaker-monitoring/http_server.py
spinnaker-monitoring/server_handlers.py
spinnaker-monitoring/spectator_handlers.py
tests/command_processor_test.py
tests/server_handlers_test.py

I've refactored it a little during the migration so that the
concrete monitoring services are injected in from main rather
than in the server_handler. This is a little cleaner.
This PR does not include any concrete services, but provides
the server infrastructure and spectator interactions.
@jtk54 or @lwander

Migrate basic server infrastructure from spinnaker/google

---

.travis.yml

@cfieber 
I'm not sure if this is going to work (never did this before)
When I look at this URL, it suggests you(?) might need to enable it for me
https://travis-ci.org/spinnaker/spinnaker-monitoring

Configure travis to run unit tests

---

config.dev/spinnaker-monitoring.yml
etc/init/spinnaker-monitoring.conf
third_party/datadog/install.sh

Run the upstart service as spinnaker rather than root.
@gardleopard
This wont affect you since your dd-agent file is readable, but now it doesnt run as root.
If you did protect your file then this installer would populate the key in the config file
since it has access to it while running as root.

Put Datadog API key into spinnaker-monitoring.yml

---

.travis.yml
install_dev.sh
spinnaker-monitoring-daemon/requirements.txt
spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py
spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-third-party/third_party/datadog/install.sh
spinnaker-monitoring-third-party/third_party/datadog/requirements.txt
spinnaker-monitoring-third-party/third_party/install_helper_functions.sh
spinnaker-monitoring-third-party/third_party/prometheus/install.sh
spinnaker-monitoring-third-party/third_party/prometheus/requirements.txt
spinnaker-monitoring-third-party/third_party/stackdriver/install.sh
spinnaker-monitoring-third-party/third_party/stackdriver/requirements.txt

Rather than pip installing all the server-specific client libraries
when the daemon is installed, only pip install them when the client
install is activated.
I dont think this is ideal, however works around a bug where
pip installing datadog client library within packer is corrupting
the images.
@jtk54

Conditionally pip install 3rd party client libraries

---

cloudbuild-prometheus.yaml

This adds a build step in order to append 'prometheus-client' to the requirements.txt file prior to building the container.
@ewiseblatt FYI

fix(cloudbuild): Adds prometheus-specific cloudbuild file

---

spinnaker-monitoring-third-party/third_party/prometheus/KitchenSinkDashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/MinimalDashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/SpecificApplicationDashboard.json

This reorganizes the panels to mirror a process flow ordering.
It separates the controller invocations into success/failure pairs.
Some of the dense count graphs were changed to stack bar graphs to
expose the underlying patterns of individual series so they arent hidden.
The latency patterns are kept as absolute line graphs since the large
outliers tend to be what's of interest.
@ttomsu

chore(prometheus): Refactored/expanded KitchenSink dashboard

---

spinnaker-monitoring-daemon/bin/spinnaker-monitoring.sh

Use `exec` so as to avoid an extraneous bash process sitting around doing nothing.  Currently when I run spinnaker-monitoring.sh, I get this output from systemctl:
```
$ sudo service spinnaker-monitoring status
● spinnaker-monitoring.service - Spinnaker monitoring service
Loaded: loaded (/lib/systemd/system/spinnaker-monitoring.service; static; vendor preset: enabled)
Active: active (running) since Fri 2017-05-12 15:52:53 UTC; 2min 48s ago
Main PID: 8478 (spinnaker-monit)
Tasks: 3
Memory: 22.8M
CPU: 304ms
CGroup: /system.slice/spinnaker-monitoring.service
├─8478 /bin/bash /opt/spinnaker-monitoring/bin/spinnaker-monitoring.sh monitor
└─8482 python /opt/spinnaker-monitoring/bin/../spinnaker-monitoring monitor
```
The extra bash process does nothing but sit around taking up a couple MB of …

`exec` python when running spinnaker-monitoring.sh

---

.gitignore
spinnaker-monitoring-third-party/third_party/prometheus/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/fiat-microservice-dashboard.json

Looks like some copy-paste errors got the wrong microservice names in two of the dashboards. Hence, if you tried to select an instance, the graphs all went blank.
Also added .gitignore for IntelliJ IDEA project data.

fix(prometheus): fix instance selectors

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/orca-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/install.sh
spinnaker-monitoring-third-party/third_party/stackdriver/minimal-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/orca-microservice-dashboard.json

cherry-pick of https://github.com/spinnaker/spinnaker-monitoring/pull/70
Earlier orca refactoring changed task.invocations metrics.
The stackdriver hystrix metrics in the dashboards thought the
"counter" metrics were counters when in fact they are gauges.

fix(dashboards): Fix stackdriver and prometheus dashboards

---

spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py
spinnaker-monitoring-daemon/tests/datadog_service_test.py

Currently, there is no way to append a set of datadog tags to metrics reported by spinnaker-monitoring.  We have multiple spinnaker instances and need to be able to distinguish between them for monitoring purposes, which is currently impossible.

allow datadog tags via env vars

---

spinnaker-monitoring-daemon/spinnaker-monitoring/metric_filter.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/tests/metric_filter_test.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py

Metric filters are managed per service rather than global.
They can be per instance, but this is not implemented.
The intent is to eventually allow the configuration of the filters to be managed
with other service configuration and let the daemon fetch it from the instance
at runtime.

chore(monitoring): Refactored metric filtering

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

This will result in the descriptor being recreated as a cumulative to avoid the
400 errors from the type mismatch. However all history will be lost.
@jtk54

fix(stackdriver): Delete gauge metric descriptors that became counters

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

fix(stackdriver): strip spaces when parsing kube CLUSTER_NAME

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py

Added SpectatorMetricTransformer to transform metric name and tags.
This is so we can change the data model without modifying the code.
While in the long run, it would be desireable to just get it right in the code,
it might not be practical or maintainable. This is intended for a few use cases
1) To support stackdriver built in metrics where we need to change the
name of the metric into the stackdriver builtin metric
2) To support monitoring systems with immutable metric schemas, such as
stackdriver where once created, new labels cannot be added. For this,
we ignore labels not present and re-aggregate the value as if it was
never partitioned against the unknown labels to begin with
3) Make the metrics more readable by imposing a different naming
scheme that is more consistent and …

feat(spectator):

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py

This adds knowledge of metric transformations into the spectator_client.
The transformation specifications are piggybacked in the existing metric
filter files using a different path into the yaml files.
@ezimanyi

feat(daemon): Integrate SpectatorMetricTransformer

---

spinnaker-monitoring-daemon/config/spinnaker-monitoring.yml
spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py

"prometheus.use_standard_notation" can be set True to use '_'
rather than ':' as the substitution character for '.' and '/'.
'-' is alwasy substituted with '_'.
The sample dashboards still assume non-standard notation.
@kskewes

chore(prometheus): Added "use_standard_notation" configuration parameter

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py

The daemon is crash-looping on startup because we're accessing a nonexistent key in the options hash. Change to use get() which will just return None instead of raising an exception.

fix(daemon): Fix KeyError on startup

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py

Empty int is 0 (should not happen, but in case in values are not present)
empty bool value is True  (because bool values are sometimes only set when False)
@ezimanyi

fix(daemon): Acocmodate empty string when transformint ING/BOOL tags

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py

transform_name is rename to a single string rather than dict
because the multiple entries arent needed in practice.
Also changed "transform_tags" to "change_tags" for simplicity.
@duftler

chore(filtering): Changed experimental transform syntax.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py

@ezimanyi 
There is also some reformatting in here to make lint happier.
The main point here is to plumb config options down to the transformation rules
so that they will be available to the next PR that will accomodate some deployment-level policies.

chore(daemon): Refactored underlying spectator module API.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py
spinnaker-monitoring-daemon/spinnaker-monitoring/util.py
spinnaker-monitoring-daemon/tests/util_test.py

Prior it was only looking where there was a yml file as well.
Now will search all directories for all files in the search path.
@jtk54

fix(daemon): refactored options to search for -local files

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py

Allowing a single meter to be split into multiple meters allows labels to be
spread among them to reduce the number of underlying time-series for a given
meter since there wont be as many permutations of label bindings.
@ezimanyi

chore(transform): Meters can transform into a list of meters

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_handlers.py

If multiple services transform the same metric, only report it once globally.
@jtk54

fix(daemon): Dont replicate transformations in explorer

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

Name should be "latencies" and use explicitBucket for the singleton value.
@jtk54

fix(stackdriver): Fixed summary support compliance

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py

Similar to extract_regex but assumes multiple capture groups will
only have one non-None value to use (i.e. the regex is acommodates
different patterns with '|')
@ezimanyi

feat(transform): Added oneof_regex transform

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

If set then when using metric transforms, transform the actual
spectator values from double to the specified value type as if
the measurements were originally of that type rather than real numbers.
@ezimanyi

feat(transform): Added transform_values option

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

Changed --summarize_timers to --summarize_compound_kinds and handle
DistributionSummary the same way.
And in stackdriver, dont create "percentile" descriptors for DISTRIBUTIONs.
@ezimanyi

feat(transform): Summarize distributions

---

spinnaker-monitoring-daemon/spinnaker-monitoring/google_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

This is functionally equivalent but factors out functionality in such a way
as to be able to reuse it when introducing ServiceControl support.
The besides moving code around, the main refactoring is how time series data
is constructed.
@jtk54 
Most of this is migrating code from stackdriver_service to google_service.
However in google_service I introduced GoogleMeasurementData.make_from_measurement and refactored the add_metric_to_timeseries() in terms of it. The make_from_measurement was derived from the old add_metric_to_timeseries implementation.

chore(stackdriver): Refactored Stackdriver into gcp_service base class

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py

There were some spectator options that were in the global dictionary.
These can be scoped into a spectator dictionary instead.
@jtk54

feat(spectator): Allow for spectator options to be scoped in spectator: dict

---

.gitignore
spinnaker-monitoring-third-party/third_party/prometheus_operator/README.md
spinnaker-monitoring-third-party/third_party/prometheus_operator/grafana-dashboard.yaml.template
spinnaker-monitoring-third-party/third_party/prometheus_operator/setup.sh
spinnaker-monitoring-third-party/third_party/prometheus_operator/spinnaker-service-monitor.yaml

The current Prometheus installation script doesn't support Kubernetes installations, and often when Spinnaker is run on K8s, Prometheus Operator (often kube-prometheus) is used for managing Prometheus.
This PR adds a script that assumes:
* Spinnaker has Prometheus metric store enabled
* Prometheus Operator is installed to the same cluster Spinnaker is on
And the script does the following:
* Add the necessary ServiceMonitor to tell Prometheus to monitor Spinnaker
* Add the Spinnaker Grafana dashboards via the recommended way of applying a configmap to the cluster
Improvements I can make to this:

Setup script for Prometheus Operator

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/aws-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/fiat-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/google-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/kubernetes-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/machine-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/orca-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/rosco-microservice-dashboard.json

so processing scripts can sub their own
This becomes important when you're running grafana across multiple pods. You need to provide a `uid` value so each pod can consistently find it.

add uid to prometheus dashboard definitions

---

spinnaker-monitoring-third-party/third_party/prometheus_operator/README.md
spinnaker-monitoring-third-party/third_party/prometheus_operator/setup.sh

It's important to put the service monitor in the same namespace as Spinnaker, so have that be the optional parameter in the setup script.

improve prometheus operator setup script

---

spinnaker-monitoring-third-party/third_party/prometheus_operator/setup.sh

With https://github.com/spinnaker/spinnaker-monitoring/pull/213, the prometheus operator setup script should generate a UID when it generates the Grafana dashboards.

generate a uid when generating the grafana dashboards for prometheus operator

---

spinnaker-monitoring-daemon/config/spinnaker-monitoring.yml
spinnaker-monitoring-daemon/requirements.txt
spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py
spinnaker-monitoring-daemon/spinnaker-monitoring/newrelic_service.py
spinnaker-monitoring-daemon/tests/newrelic_service_test.py

Adds a New Relic service which can report raw metrics to New Relic insights using the metrics api and the New Relic Python SDK. Includes tests and updates to configuration docs but not a local install script or pre-built dashboards.
We have been running this code in a test Spinnaker cluster for ~1.5 weeks now without issues. We've also built the config into halyard in a branch [here](https://github.com/newrelic-forks/spinnaker-halyard/tree/newrelic-metric-store) for use configuring the monitoring daemon.

feat: adds new relic integration

---

spinnaker-monitoring-daemon/spinnaker-monitoring/http_server.py

Fixes spinnaker/spinnaker#4980
ecba3ea4cca94253f10f97ae315ad9116da12055 added a call to encode the response body before sending it to the server if the body is of type str.
This is the correct behavior for python 3, where str represents a an unencoded string, but is incorrect for python 2. In python 2, str represents an already-encoded string and unicode represents an unencoded string.
This is breaking for prometheus monitoring, which is sending already-encoded bytes to the respond() function. In python 2, those have type str, so we're trying to re-encode them. This works fine as long as there are only ASCII characters in the string, but breaks otherwise.
In order to support both python 2 and 3, try to use 'unicode' (as exists in 2) and if it's absent assign str to unicode.

fix(encoding): Fix double-encoding of HTTP response

---

spinnaker-monitoring-daemon/config/spinnaker-monitoring.yml
spinnaker-monitoring-daemon/requirements.txt

Pins the `newrelic-telemetry-sdk` version as it appears there are breaking changes in `0.2.0`.
This PR started with 2 spelling corrections; CI was [failing](https://travis-ci.org/spinnaker/spinnaker-monitoring/builds/611577511?utm_medium=notification&utm_source=github_status) with the following:
```bash
Running ./tests/newrelic_service_test.py
> Building 28% > :spinnaker-monitoring-daemon:test> Building 28% > :spinnaker-monitoring-daemon:test======================================================================
ERROR: test_make_new_relic_service (__main__.NewRelicServiceFactoryTest)
test if options are being passed through correctly by checking url of metric client
----------------------------------------------------------------------
Traceback (most recent call last):
File …
```

fix(daemon): pin newrelic-telemetry-sdk version + spelling corrections

---

spinnaker-monitoring-daemon/spinnaker-monitoring/newrelic_service.py
spinnaker-monitoring-daemon/tests/newrelic_service_test.py

Applying tags to the `newrelic` monitoring daemon are not working as expected. Erroring with the following:
```bash
/usr/local/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/local/lib/python2.7/site-packages/google': missing __init__.py
file, filename, etc = imp.find_module(subname, path)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/opt/spinnaker-monitoring/bin/__main__.py", line 194, in <module>
main(search_path)
File "/opt/spinnaker-monitoring/bin/__main__.py", line 170, in main
options['command'], options, all_command_handlers)
File …
```

fix(daemon): fix newrelic tagging

---

.gcloudignore
Dockerfile.compile
build.gradle

Three things:
* We need to add a `.gcloudignore` so that the `.git` directory gets uploaded
* We need to use `openjdk:8` so that we can run gradle
* We need to add an empty `javadoc` task so that we can use `-x javadoc` (since all the debian builds use the same gradle command)

chore(gcb): make the debs buildable on GCB

---

spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py

When exporting to DataDog, the metrics name being exported has one more service name being prepended to it. This change removes the code that prepends service name to metric name after normalisation.
Fixes: spinnaker/spinnaker#5311

fix(datadog): Remove additional service name

---

spinnaker-monitoring-daemon/halconfig/README.md
spinnaker-monitoring-third-party/halconfig/spinnaker-monitoring-third-party.yml

* refactor(config): remove unused spinnaker-monitoring-third-party halconfig 
The spinnaker-monitoring-third-party package does not actually have any Halyard-generated config, and in fact I can't find any references to spinnaker-monitoring-third-party.yml anywhere in this repository. Based on documentation, spinnaker-monitoring-third-party needs to be installed as a debian package, and then users are expected to run one or more of the dashboard installation scripts contained in the package to install third-party dashboards.
* feat(config): deprecate spinnaker-monitoring-daemon halconfig 
Originally, I had assumed that /spinnaker-monitoring-daemon/config/spinnaker-monitoring.yml contained defaults that were merged with Halyard-mounted spinnaker-monitoring.yml and …

refactor(config): remove unused spinnaker-monitoring-third-party halconfig 

---

Dockerfile.compile

The Spinnaker gradle plugin is compiled against Java 11, so we can't use Java 8 anymore. This uses the same OS to compile as the other Spinnaker projects.

chore(java11): use Java 11 to run Gradle

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/release_info.sh
build.gradle
gradle.properties

We need to publish a debian package to Google Artifact Registry for use
by Halyard as part of the BOM.
```
$ ORG_GRADLE_PROJECT_version=1.2.3 ./gradlew buildDeb
> Task :spinnaker-monitoring-daemon:buildDeb
> Task :spinnaker-monitoring-third-party:buildDeb
<snip>
$ find . -name *.deb
./spinnaker-monitoring-third-party/build/distributions/spinnaker-monitoring-third-party_1.2.3_all.deb
./spinnaker-monitoring-daemon/build/distributions/spinnaker-monitoring-daemon_1.2.3_all.deb
```

chore(ci): Add GHA for last publish of Monitoring Daemon 

---

build.gradle

to avoid
```
Run ./gradlew --info publishDebToArtifactRegistry
* What went wrong:
Task 'publishDebToArtifactRegistry' not found in root project 'spinnaker-monitoring'.
```
from https://github.com/spinnaker/spinnaker-monitoring/runs/6071300143?check_suite_focus=true

chore(ci): make a publishDebToArtifactRegistry task at the top level

---

.github/workflows/release.yml
.mergify.yml

Previous release tools would publish basic halconfig profiles to GCS
bucket: [https://console.cloud.google.com/storage/browser/halconfig/`<service>`/`<version>`/*](https://console.cloud.google.com/storage/browser/halconfig/%60%3Cservice%3E%60/%60%3Cversion%3E%60/*)
Where `<service>` might be `rosco` and `<version>` is our git tag, eg: `v1.2.3`.
Halyard downloads these profiles during `hal deploy apply`.
As the profiles are deprecated it would be ideal to remove from Halyard
but it may break users workflows.
For now we can upload the files as part of our regular service 'release'
flow (git tag <version> && git push) using GHA.

chore(ci): Upload halconfigs to GCS on Tag push
