spinnaker/spinnaker-monitoring

requirements.txt
spinnaker-monitoring/__main__.py
spinnaker-monitoring/datadog_handlers.py
spinnaker-monitoring/datadog_service.py

@lwander or @jtk54 
(essentially my prototype implementation with minor tweaks for the server refactoring)
The json files will come later in the installation PR

Added Datadog support.

---

conf.dev/prometheus.conf
requirements.txt
spinnaker-monitoring/__main__.py
spinnaker-monitoring/prometheus_service.py

@lwander or @jtk54 
(essentially my prototype implementation with minor tweaks for the server refactoring)
The json files will come later in the installation PR

Added Prometheus support.

---

conf.dev/stackdriver.conf
requirements.txt
spinnaker-monitoring/__main__.py
spinnaker-monitoring/stackdriver_handlers.py
spinnaker-monitoring/stackdriver_service.py
tests/stackdriver_handlers_test.py
tests/stackdriver_service_test.py

@lwander or @jtk54 
(essentially my prototype implementation with minor tweaks for the server refactoring)
The json files will come later in the installation PR

Added Stackdriver support.

---

spinnaker-monitoring/__main__.py
spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring/spectator_client.py

Fixed typos lost in translation

---

tests/run_tests.sh

Added script to run all the tests.

---

README.md
create_install_tar.sh
install/create_install_tar.sh
install/datadog/KitchenSinkTimeboard.json
install/datadog/MinimalTimeboard.json
install/datadog/SpecificApplicationTimeboard.json
install/datadog/install.sh
install/install-spinnaker-monitoring.sh
install/prometheus/KitchenSinkDashboard.json
install/prometheus/MachineDashboard.json
install/prometheus/MinimalDashboard.json
install/prometheus/SpecificApplicationDashboard.json
install/prometheus/install.sh
install/prometheus/node_exporter.conf
install/prometheus/prometheus.conf
install/prometheus/spinnaker-prometheus.yml
install/sample_filter.json
install/stackdriver/MinimalDashboard.json
install/stackdriver/install.sh

@lwander or @jtk54 
This is the last of the initial baseline
Note the datadog/prometheus/stackdriver directories under install
are independent of the install scripts that invoke them. They are
globbed into this PR for review convienence.
The bash scripts are temporary. This will be replaced with a debian package
and gradle. For now this is carrying forward my prototype as a starting point.

Added initial install.

---

spinnaker-monitoring/datadog_service.py
tests/datadog_service_test.py

Fixed install and datadog batching.

---

config.dev/spinnaker-monitoring.yml
spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring/server_handlers.py

Support Prometheus PushGateway

---

third_party/prometheus/install.sh
third_party/prometheus/node_exporter.conf
third_party/prometheus/prometheus.conf
third_party/prometheus/pushgateway-prometheus.yml
third_party/prometheus/pushgateway.conf

Deconstructed prometheus install

---

third_party/prometheus/MachineDashboard.json
third_party/prometheus/install.sh

Fixed install and other dashboard tweaks.
@ttomsu

Show network throughput on dashboard

---

config.dev/spinnaker-monitoring.yml
spinnaker-monitoring/http_server.py
spinnaker-monitoring/server_handlers.py
tests/http_server_test.py

Configure host for other than localhost

---

Dockerfile
cloudbuild.yaml

@ewiseblatt These are the edits I've made from the past two days.
Now under the correct user.

Dockerfile and cloudbuild.yaml files

---

Dockerfile

rm registry arg

---

spinnaker-monitoring-daemon/bin/spinnaker-monitoring.sh
spinnaker-monitoring-daemon/etc/init/spinnaker-monitoring.conf
spinnaker-monitoring-daemon/spinnaker-monitoring.yml
spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-third-party/pkg_scripts/postInstall.sh
spinnaker-monitoring-third-party/third_party/datadog/install.sh
spinnaker-monitoring-third-party/third_party/prometheus/install.sh
spinnaker-monitoring-third-party/third_party/stackdriver/install.sh

- Added postInstall script
- Check flags in install scripts
- Monitor to stdout by default and only a log file when asked.
- dont both setuid and run as sudo in .conf
@lwander

Misc bug fixes:

---

cloudbuild.yaml
spinnaker-monitoring-daemon/Dockerfile
spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py

Fix cloudbuild, disable SSL verification.

---

README.md

fix(README): Correcting docs URL

---

install_dev.sh

fix(dev): Fixed installation in a development environment.

---

spinnaker-monitoring-daemon/tests/http_server_test.py

fix(test): Fixed test broken by last minute change in previous commit.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/server_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/datadog_service_test.py

fix(config): Fixed some provider-related config

---

spinnaker-monitoring-third-party/third_party/prometheus/KitchenSinkDashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/aws-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/fiat-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/google-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/install.sh
spinnaker-monitoring-third-party/third_party/stackdriver/kubernetes-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/minimal-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/orca-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/rosco-microservice-dashboard.json

feat(stackdriver): Added stackdriver dashboards

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/fiat-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/rosco-microservice-dashboard.json

fix(prometheus): Use placeholder for datasource in template sections

---

spinnaker-monitoring-third-party/third_party/prometheus/install.sh

@lwander 
I'm configuring the passwords as I noticed I omitted when we looked this over today.
I also bumped the version numbers and restructured it to make it easier to update a version.
And I noticed in the grafana install that there was a debian repo so I switched to using that.
Prometheus still does not come from a repo.
I'm not sure what you are doing in halyard but this is a more maintainable starting point.
Also, when testing this (without the daemon installed) it was failing because pip wasnt installed (it is introduced by the daemon).

fix(prometheus): Configure passwords

---

spinnaker-monitoring-third-party/third_party/stackdriver/aws-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/fiat-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/google-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/install.sh
spinnaker-monitoring-third-party/third_party/stackdriver/kubernetes-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/minimal-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/orca-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/rosco-microservice-dashboard.json

fix(stackdriver): Updated stackdriver dashboards

---

spinnaker-monitoring-third-party/third_party/prometheus/install.sh
spinnaker-monitoring-third-party/third_party/prometheus/prometheus.conf

fix(prometheus): Fixed upstart config

---

spinnaker-monitoring-third-party/third_party/stackdriver/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/install.sh
spinnaker-monitoring-third-party/third_party/stackdriver/orca-microservice-dashboard.json

fix(stackdriver): Fixed installer pre-requisites and orca dashboard typo

---

spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py
spinnaker-monitoring-daemon/tests/datadog_service_test.py

The current regex expression that extracts api keys from the datadog
config file does not work well. As python config parser supports the
config file format, it is better to leverage it directly
@lwander @ewiseblatt PTAL

fix(datadog): Use configparser to read datadog config file

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/install.sh
spinnaker-monitoring-third-party/third_party/prometheus/machine-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/prometheus.conf

feat(prometheus): Various prometheus monitoring enhancements

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/aws-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/google-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/install.sh
spinnaker-monitoring-third-party/third_party/prometheus/kubernetes-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/machine-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json

@lwander 
some more tweaking. I'll merge this after I have a chance to try it out over a few instances, but need some other repository PRs merged before I can build the BOM to do that.

chore(prometheus): Updated google and system dashboards

---

spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json

fix(prometheus): Fixed units displayed on minimalist dashboard

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/aws-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/fiat-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/google-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/kubernetes-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/machine-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/orca-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/rosco-microservice-dashboard.json

@ttomsu 
To try this out
./spinnaker-monitoring/spinnaker-monitoring-third-party/third_party/prometheus/install.sh --dashboards_only --overwrite

feat(prometheus): Sort tooltips and template values in dashboards

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json

fix(prometheus): Fixed metric breakout by application name

---

spinnaker-monitoring-daemon/Dockerfile

chore(docker): Upgrade base image (#2298)

---

spinnaker-monitoring-third-party/third_party/prometheus/install.sh
spinnaker-monitoring-third-party/third_party/prometheus/machine-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/node_exporter.conf
spinnaker-monitoring-third-party/third_party/prometheus/prometheus.conf

feat(prometheus): upgrade to XYZ

---

spinnaker-monitoring-third-party/third_party/install_helper_functions.sh
spinnaker-monitoring-third-party/third_party/prometheus/install.sh
spinnaker-monitoring-third-party/third_party/prometheus/pushgateway.conf
spinnaker-monitoring-third-party/third_party/prometheus/systemd/node_exporter.service
spinnaker-monitoring-third-party/third_party/prometheus/systemd/prometheus.service
spinnaker-monitoring-third-party/third_party/prometheus/systemd/pushgateway.service
spinnaker-monitoring-third-party/third_party/prometheus/upstart/node_exporter.conf
spinnaker-monitoring-third-party/third_party/prometheus/upstart/prometheus.conf
spinnaker-monitoring-third-party/third_party/prometheus/upstart/pushgateway.conf

feat(prometheus): Install for systemd in addition to upstart

---

spinnaker-monitoring-daemon/registry.dev/kayenta.yml
spinnaker-monitoring-daemon/tests/spectator_client_test.py

chore(monitoring): Add kayenta configuration.

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/orca-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/install.sh
spinnaker-monitoring-third-party/third_party/stackdriver/minimal-dashboard.json
spinnaker-monitoring-third-party/third_party/stackdriver/orca-microservice-dashboard.json

Fix dashboards

---

spinnaker-monitoring-daemon/etc/init/spinnaker-monitoring.conf

fix(upstart): Fixed upstart logging

---

spinnaker-monitoring-daemon/spinnaker-monitoring/metric_filter.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/tests/metric_filter_test.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py

Deprecated experimental --prototype_path, which is unlikely to be in use
@jtk54

feat(filter): Added --metric_filter_path

---

spinnaker-monitoring-third-party/third_party/prometheus/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/front50-microservice-dashboard.json

* sum counter over instances for clouddriver.google.operationWaits metric
* avg gauge for front50.storageServiceSupport.cacheAge
@jtk54

feat(prometheus): Fix sample dashboard panels

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py

Sometimes spectator has NaN values. Strip those out because they break some
monitoring systems.
@jtk54

fix(daemon): Handle NaN responses

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

chore(stackdriver): linted stackdriver support

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

This will result in the descriptor being recreated as a gauge to avoid the
400 errors from the type mismatch. However all history will be lost.
@jtk54

fix(stackdriver): Delete counter metric descriptors that became gauges.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py

feat(filter): look for filters dir.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_handlers.py

feat(admin): Show meter types in admin UI

---

spinnaker-monitoring-daemon/Dockerfile

https://github.com/spinnaker/spinnaker/issues/3147

chore(docker): run as spinnaker

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/tests/metric_filter_test.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py

fix(daemon): Use load YAML config securely.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py
spinnaker-monitoring-third-party/third_party/datadog/KitchenSinkTimeboard.json

Remove deprecated

---

spinnaker-monitoring-daemon/spinnaker-monitoring/http_server.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_handlers.py

@jtk54 
To provide some feedback adjusting metric filters to see what's being ignored (vs what's included)

feat(server): show/explore metrics without filtering.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/http_server.py
spinnaker-monitoring-daemon/spinnaker-monitoring/server_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py

feat(stackdriver): identify used and unused custom metric descriptors

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py

@jtk54 
Heuristic is the same but more readable organization.

chore(prometheus): refactored daemon prometheus support

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

feat(daemon): Added PercentileTimer and Distribution awareness.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

fix(stackdriver): Fixed GCP managed resource identities

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py
spinnaker-monitoring-daemon/spinnaker-monitoring/server_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py

chore(daemon): Added more logging

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py

fix(terminate): Add signal handler for SIGTERM to terminate.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py

fix(terminate): Add signal handler for SIGTERM to terminate. (#100)

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

Do not merge until this is validated to be working at HEAD

Pull in a few fixes for 1.10.2 

---

spinnaker-monitoring-daemon/config/spinnaker-monitoring.yml
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

chore(daemon): Cleanuped up using configuration file

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py

Patch 10.x with recent prometheus fixes

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py

If the default.yml file is present then it should provide the baseline
with the service-specific file layered on top.
@jtk54

fix(daemon): Fix transform specification inheritence.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py

feat(daemon): Add spin_variant tag if spectator.inject_service_tag

---

spinnaker-monitoring-third-party/third_party/prometheus/application-drilldown-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/aws-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/clouddriver-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/echo-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/fiat-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/front50-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/gate-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/google-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/igor-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/kubernetes-platform-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/minimal-spinnaker-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/orca-microservice-dashboard.json
spinnaker-monitoring-third-party/third_party/prometheus/rosco-microservice-dashboard.json

Recently Prometheus metric names were updated. This PR updates dashboards to use new naming scheme.

fix(grafana): Update Prometheus dashboards

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py

fix(prometheus): Remove - from service names in prometheus metrics.

---

spinnaker-monitoring-daemon/config/spinnaker-monitoring.yml
spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py
spinnaker-monitoring-daemon/tests/datadog_service_test.py

The fix is #240-255, the rest is a guard and tests.
I didnt try this for real, only wrote a test. Please confirm.

fix(datadog): Added --datadog_use_types to publish types with metrics.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py

This does some extra transformation work but does not yet implement
anything to take advantage of it. However this should facilitate
experimenting with taking that next step.
@jtk54

feat(daemon): Plumb experimental transformation per-* tags

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py
spinnaker-monitoring-daemon/spinnaker-monitoring/server_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py

Also added loglevel to messages.
@jtk54

fix(daemon): Changed default --log_level from INFO to ERROR to console.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py

fix(transform): Tolerate UNKNOWN values

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py

fix(experimental): Experimental fixes

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

fix(stackdriver): Fixed command-line override precedence

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

Stackdriver refactor

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py

fix(config): Can set log_level (and log_dir) from config file.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

chore(stackdriver): Added unit tests for writing timeseries data.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py

feat(daemon): Can specify 'Summary' metric type.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py

fix(config): Look for configuration file in .hal/default/profiles

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py

chore(prometheus): deprecate prometheus_add_Source_metalabels

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

@ezimanyi 
This is the last PR in the sequence.

feat(stackdriver): Add summary descriptor support

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

chore(stackdriver): can easily disable autofix labels

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

This is a temporary workaround for difficulty getting counts from distributions.
@jtk54

feat(stackdriver): Added option to store counter along with distribution

---

spinnaker-monitoring-daemon/spinnaker-monitoring/prometheus_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py

feat(transform): Control whether tag values are typed or not

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

fix(stackdriver): Fixed aws_ec2_instance

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py

fix(stackdriver): Fixed distribution count counter.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

Stackdriver now handles this internally so the errors should no longer occur.
@jtk54

chore(stackdriver): Removed unknown label error handling.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

feat(stackdriver): Can configure a 'generic_task' monitored resource.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

feat(stackdriver): Config spinnaker metric prefix

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

feat(stackdriver): Config for discovery_url

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

feat(transform): Keep track of percentile bucketing.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/__main__.py
spinnaker-monitoring-daemon/spinnaker-monitoring/gcp_service_control_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/google_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

This may not yet be in a working state but is probably close and should not
impact other functionality.
@jtk54

feat(google): Experimental support for ServiceControl service

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py

From __count to _count to be compliant to stackdriver naming policies.
@jtk54

chore(stackdriver): Changed distribution counter naming pattern

---

spinnaker-monitoring-daemon/spinnaker-monitoring/google_service.py

fix(stackdriver): Ensure GenericTask label values are strings.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py

Stackdriver labels can have typed values however must still be encoded as strings when writing.
@jtk54

fix(stackdriver): write labels as strings

---

spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py

chore(stackdriver): Use meter name as display name.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/command_processor.py
spinnaker-monitoring-daemon/spinnaker-monitoring/datadog_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/google_service.py
spinnaker-monitoring-daemon/spinnaker-monitoring/http_server.py
spinnaker-monitoring-daemon/spinnaker-monitoring/metric_filter.py
spinnaker-monitoring-daemon/spinnaker-monitoring/server_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_metric_transformer.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_descriptors.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_handlers.py
spinnaker-monitoring-daemon/spinnaker-monitoring/stackdriver_service.py
spinnaker-monitoring-daemon/tests/datadog_service_test.py
spinnaker-monitoring-daemon/tests/http_server_test.py
spinnaker-monitoring-daemon/tests/spectator_client_test.py
spinnaker-monitoring-daemon/tests/spectator_metric_transformer_test.py
spinnaker-monitoring-daemon/tests/stackdriver_service_test.py
spinnaker-monitoring-third-party/third_party/stackdriver/requirements.txt

chore(daemon): Python3 fixes.

---

spinnaker-monitoring-daemon/spinnaker-monitoring/google_service.py

fix(stackdriver): use tags_are_typed_strings.

---

Dockerfile.compile
Dockerfile.slim
Dockerfile.ubuntu

See spinnaker/buildtool#14
I forgot this one.

chore(build): Update Dockerfiles for new cloudbuild configs

---

.gitignore
.mergify.yml

Also add venv to .gitignore so we don't accidentally check in our python virtual environments.

feat(mergify): Add mergify config

---

build.gradle
spinnaker-monitoring-daemon/spinnaker-monitoring-daemon.gradle
spinnaker-monitoring-third-party/spinnaker-monitoring-third-party.gradle

chore(build): keep the release part of the version if provided

---

.github/workflows/release.yml

Change may need to be cherry picked?

fix(release): Fix GHA yaml syntax

---

.github/workflows/build.yml

Not sure why we were trying to publish during a branch build workflow.

fix(builds): Rm publishing params from build.yml GHA
